import Head from "next/head";
import Link from "next/link";
import { Inter } from "@next/font/google";
import { Footer } from "src/components/Footer";
import { Main } from "src/components/Main";
import { Header } from "src/components/Header";
import { useCallback, useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [foo, setFoo] = useState(1);
  const [text, setText] = useState("");
  const [isShow, setIsShow] = useState(true);
  const [array, setArray] = useState([1, 2, 3]);

  const handleAdd = useCallback(() => {
    alert("abc");
  }, []);
  const handleClick = useCallback(() => {
    console.log(foo);
    if (foo < 10) {
      setFoo((foo) => foo + 1);
    }
  }, [foo]);

  const handleChange = useCallback((e) => {
    setText(e.target.value.trim());
  }, []);

  const handleDisplay = useCallback(() => {
    setIsShow((isShow) => !isShow);
  }, []);

  useEffect(() => {
    console.log("foo");
    document.body.style.backgroundColor = "lightblue";
    return () => {
      document.body.style.backgroundColor = "";
    };
  }, [foo]);

  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      {isShow ? <h1>{foo}</h1> : null}
      <button onClick={handleClick}>ボタン</button>
      <button onClick={handleDisplay}>
        {isShow ? "ひひょうじ" : "ひょうじ"}
      </button>
      <input type="text" value={text} onChange={handleChange} />
      <button onClick={handleAdd}>handleAdd</button>
      <ul>
        {array.map((item) => {
          return <li key={item}>{item}</li>;
        })}
      </ul>
      <Main page="index"></Main>

      <Footer />
    </>
  );
}
